"""The JSON-only YouTube Shorts pipeline.

Episode JSON provides narration, metadata, comment, hashtags and visual search
prompts.  No script, metadata, visual prompt, or comment is generated by AI at
runtime.
"""

import os
import sys
import traceback
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from analytics_tracker import save_video_data
from content_loader import (
    claim_next_episode,
    episode_id,
    mark_episode_uploaded,
    release_episode_claim,
)
from editor import create_video
from fetch_footage import fetch_footage
from playlist_config import get_playlist_id
from thumbnail_generator import create_thumbnail
from tts_generator import generate_voice
from youtube_uploader import post_comment, upload_video


SCRIPT_PATH = "script.txt"
VIDEO_OUTPUT = "output/final_short.mp4"
THUMBNAIL_OUTPUT = "output/thumbnail.jpg"


def verify_file(path, message):
    if not os.path.exists(path):
        raise FileNotFoundError(message)


def save_script(script):
    with open(SCRIPT_PATH, "w", encoding="utf-8") as file:
        file.write(script)


def clean_text(value):
    return " ".join(str(value or "").replace("**", "").split())


def build_script(episode):
    parts = [episode.get("hook", ""), episode.get("script", ""), episode.get("cta", "")]
    return "\n\n".join(clean_text(part) for part in parts if clean_text(part))


def build_description(episode):
    description = clean_text(episode.get("description"))
    hashtags = episode.get("hashtags", [])
    if isinstance(hashtags, str):
        hashtags = hashtags.split()
    hashtags = [tag if str(tag).startswith("#") else f"#{tag}" for tag in hashtags]
    return "\n\n".join(part for part in (description, " ".join(dict.fromkeys(hashtags))) if part)


def run_series_pipeline():
    started_at = datetime.now()
    episode = claim_next_episode()
    if not episode:
        print("No unexecuted JSON episode remains in the active series.")
        return

    series_name = episode["series"]
    item_id = episode_id(episode)
    try:
        title = clean_text(episode["title"])
        script = build_script(episode)
        description = build_description(episode)
        comment = clean_text(episode.get("comment", ""))
        if not title or not script or not description or not comment:
            raise ValueError("Episode JSON must resolve title, script, description, hashtags, and comment")

        print(f"Running JSON episode: {item_id}")
        save_script(script)
        verify_file(SCRIPT_PATH, "script.txt missing")

        create_thumbnail(title)
        verify_file(THUMBNAIL_OUTPUT, "Thumbnail missing")

        footage_count = fetch_footage(script, episode["visual_queries"])
        if footage_count < 3:
            raise RuntimeError("Not enough new footage downloaded")

        generate_voice()
        verify_file("assets/audio/narration.wav", "Narration missing")
        create_video()
        verify_file(VIDEO_OUTPUT, "Final video missing")

        upload_result = upload_video(
            title=title,
            description=description,
            video_path=VIDEO_OUTPUT,
            playlist_id=get_playlist_id(series_name),
        )
        if not upload_result or not upload_result.get("video_id"):
            raise RuntimeError("Upload failed or did not return a video_id")

        # Persist completion immediately after YouTube confirms the upload.
        # Commenting and analytics are helpful follow-up work, but a failure in
        # either must never cause the uploaded JSON item to run again.
        mark_episode_uploaded(series_name, item_id=item_id, upload_result=upload_result)
        try:
            post_comment(video_id=upload_result["video_id"], comment_text=comment)
            save_video_data(
                title=title,
                topic=series_name,
                video_id=upload_result["video_id"],
                video_url=upload_result.get("video_url", ""),
            )
        except Exception as follow_up_error:
            print(f"Upload is complete; optional follow-up failed: {follow_up_error}")
        elapsed = (datetime.now() - started_at).total_seconds()
        print(f"JSON pipeline completed in {elapsed:.1f} seconds.")
    except BaseException:
        release_episode_claim(series_name, item_id)
        raise


if __name__ == "__main__":
    try:
        run_series_pipeline()
    except KeyboardInterrupt:
        print("Pipeline stopped manually. The episode claim was released.")
    except Exception as error:
        print(f"PIPELINE FAILED: {error}")
        traceback.print_exc()
